/* tslint:disable */
/* eslint-disable */
/**
 * Test API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: testing@api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './api/apply-api';
export * from './api/generate-api';
export * from './api/help-api';
export * from './api/participant-api';
export * from './api/question-api';
export * from './api/register-api';
export * from './api/training-generate-api';

