/* tslint:disable */
/* eslint-disable */
/**
 * Test API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: testing@api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { IsExistParticipant } from '../model';
/**
 * ParticipantApi - axios parameter creator
 * @export
 */
export const ParticipantApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} mobileNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        participantExistsRead: async (mobileNumber: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'mobileNumber' is not null or undefined
            assertParamExists('participantExistsRead', 'mobileNumber', mobileNumber)
            const localVarPath = `/participant/{mobile_number}/exists`
                .replace(`{${"mobile_number"}}`, encodeURIComponent(String(mobileNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Basic required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ParticipantApi - functional programming interface
 * @export
 */
export const ParticipantApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ParticipantApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} mobileNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async participantExistsRead(mobileNumber: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IsExistParticipant>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.participantExistsRead(mobileNumber, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ParticipantApi - factory interface
 * @export
 */
export const ParticipantApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ParticipantApiFp(configuration)
    return {
        /**
         * 
         * @param {string} mobileNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        participantExistsRead(mobileNumber: string, options?: any): AxiosPromise<IsExistParticipant> {
            return localVarFp.participantExistsRead(mobileNumber, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for participantExistsRead operation in ParticipantApi.
 * @export
 * @interface ParticipantApiParticipantExistsReadRequest
 */
export interface ParticipantApiParticipantExistsReadRequest {
    /**
     * 
     * @type {string}
     * @memberof ParticipantApiParticipantExistsRead
     */
    readonly mobileNumber: string
}

/**
 * ParticipantApi - object-oriented interface
 * @export
 * @class ParticipantApi
 * @extends {BaseAPI}
 */
export class ParticipantApi extends BaseAPI {
    /**
     * 
     * @param {ParticipantApiParticipantExistsReadRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ParticipantApi
     */
    public participantExistsRead(requestParameters: ParticipantApiParticipantExistsReadRequest, options?: any) {
        return ParticipantApiFp(this.configuration).participantExistsRead(requestParameters.mobileNumber, options).then((request) => request(this.axios, this.basePath));
    }
}
