/* tslint:disable */
/* eslint-disable */
/**
 * Test API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: testing@api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { TaskRegister } from '../model';
/**
 * RegisterApi - axios parameter creator
 * @export
 */
export const RegisterApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {TaskRegister} data 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerCreate: async (data: TaskRegister, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'data' is not null or undefined
            assertParamExists('registerCreate', 'data', data)
            const localVarPath = `/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Basic required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(data, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RegisterApi - functional programming interface
 * @export
 */
export const RegisterApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RegisterApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {TaskRegister} data 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerCreate(data: TaskRegister, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TaskRegister>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerCreate(data, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * RegisterApi - factory interface
 * @export
 */
export const RegisterApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RegisterApiFp(configuration)
    return {
        /**
         * 
         * @param {TaskRegister} data 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerCreate(data: TaskRegister, options?: any): AxiosPromise<TaskRegister> {
            return localVarFp.registerCreate(data, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for registerCreate operation in RegisterApi.
 * @export
 * @interface RegisterApiRegisterCreateRequest
 */
export interface RegisterApiRegisterCreateRequest {
    /**
     * 
     * @type {TaskRegister}
     * @memberof RegisterApiRegisterCreate
     */
    readonly data: TaskRegister
}

/**
 * RegisterApi - object-oriented interface
 * @export
 * @class RegisterApi
 * @extends {BaseAPI}
 */
export class RegisterApi extends BaseAPI {
    /**
     * 
     * @param {RegisterApiRegisterCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RegisterApi
     */
    public registerCreate(requestParameters: RegisterApiRegisterCreateRequest, options?: any) {
        return RegisterApiFp(this.configuration).registerCreate(requestParameters.data, options).then((request) => request(this.axios, this.basePath));
    }
}
