/* tslint:disable */
/* eslint-disable */
/**
 * Test API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: testing@api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ReactionTime } from './reaction-time';

/**
 * 
 * @export
 * @interface ApplyTask
 */
export interface ApplyTask {
    /**
     * 
     * @type {string}
     * @memberof ApplyTask
     */
    mobile_number: string;
    /**
     * 
     * @type {Array<ReactionTime>}
     * @memberof ApplyTask
     */
    reaction_times: Array<ReactionTime>;
    /**
     * 
     * @type {string}
     * @memberof ApplyTask
     */
    next_date?: string;
    /**
     * 
     * @type {number}
     * @memberof ApplyTask
     */
    score?: number;
    /**
     * 
     * @type {number}
     * @memberof ApplyTask
     */
    reaction_time_mean?: number;
}


