/* tslint:disable */
/* eslint-disable */
/**
 * Test API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: testing@api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Health
 */
export interface Health {
    /**
     * 
     * @type {number}
     * @memberof Health
     */
    get_covid_19: number;
    /**
     * 
     * @type {boolean}
     * @memberof Health
     */
    get_drug: boolean;
    /**
     * 
     * @type {string}
     * @memberof Health
     */
    mental_disorder?: string;
}


