/* tslint:disable */
/* eslint-disable */
/**
 * Test API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: testing@api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IsExistParticipant
 */
export interface IsExistParticipant {
    /**
     * 
     * @type {boolean}
     * @memberof IsExistParticipant
     */
    is_exist?: boolean;
}


