/* tslint:disable */
/* eslint-disable */
/**
 * Test API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: testing@api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Participant
 */
export interface Participant {
    /**
     * 
     * @type {string}
     * @memberof Participant
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Participant
     */
    family_name: string;
    /**
     * 
     * @type {number}
     * @memberof Participant
     */
    birth_year?: number;
    /**
     * 
     * @type {number}
     * @memberof Participant
     */
    education_level: number;
    /**
     * 
     * @type {string}
     * @memberof Participant
     */
    mobile_number: string;
    /**
     * 
     * @type {string}
     * @memberof Participant
     */
    gender: ParticipantGenderEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum ParticipantGenderEnum {
    Male = 'male',
    Female = 'female'
}



