/* tslint:disable */
/* eslint-disable */
/**
 * Test API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: testing@api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReactionTime
 */
export interface ReactionTime {
    /**
     * 
     * @type {number}
     * @memberof ReactionTime
     */
    image?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ReactionTime
     */
    reaction_time?: number | null;
}


