/* tslint:disable */
/* eslint-disable */
/**
 * Test API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: testing@api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TaskImage } from './task-image';

/**
 * 
 * @export
 * @interface TaskInfo
 */
export interface TaskInfo {
    /**
     * 
     * @type {Array<TaskImage>}
     * @memberof TaskInfo
     */
    images: Array<TaskImage>;
    /**
     * 
     * @type {Array<number>}
     * @memberof TaskInfo
     */
    orders: Array<number>;
}


