/* tslint:disable */
/* eslint-disable */
/**
 * Test API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: testing@api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Health } from './health';
import { Participant } from './participant';
import { ParticipantQuestionAnswer } from './participant-question-answer';

/**
 * 
 * @export
 * @interface TaskRegister
 */
export interface TaskRegister {
    /**
     * 
     * @type {Participant}
     * @memberof TaskRegister
     */
    participant: Participant;
    /**
     * 
     * @type {Health}
     * @memberof TaskRegister
     */
    health: Health;
    /**
     * 
     * @type {Array<ParticipantQuestionAnswer>}
     * @memberof TaskRegister
     */
    answers: Array<ParticipantQuestionAnswer>;
}


